server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888/
  zipkin:
    base-url: http://zipkin-service:9411/
  cloud:
    config:
      discovery:
        profile: dev
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movie-service
          uri: http://localhost:8001
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: catalog-service
          uri: http://localhost:8002
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
